### ISSUE TITLE
NameError: name 'SerialException' is not defined

### ISSUE THREAD

**Issue by process1183** [AtsushiSakai/PyRoombaAdapter#13]
Hi. If you try to create a new instance of `PyRoombaAdapter` without the serial port being present, it raises a `SerialException`. However, this exception is not defined in `pyroombaadapter.py` and causes a `NameError` exception to be raised. This is an easy fix (see commit https://github.com/process1183/PyRoombaAdapter/commit/8699ffc2c03d52e2a7a646906db6b6f00e278bc5). After fixing the `SerialException` definition, I ran into another issue: If opening the serial port fails, then the `__del__()` method also throws an exception. Here's an example of this:

```
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyroombaadapter
>>> roomba = pyroombaadapter.PyRoombaAdapter("/dev/doesnotexist")
Cannot find serial port. Plase reconnect it.
Exception ignored in: <function PyRoombaAdapter.__del__ at 0x7f96d2691b70>
Traceback (most recent call last):
  File "/home/josh/projects/forked/PyRoombaAdapter/pyroombaadapter/pyroombaadapter.py", line 86, in __del__
    self._send_cmd(self.CMD["Start"])  # move to passive mode
  File "/home/josh/projects/forked/PyRoombaAdapter/pyroombaadapter/pyroombaadapter.py", line 608, in _send_cmd
    self.serial_con.write(bytes([cmd]))
AttributeError: 'PyRoombaAdapter' object has no attribute 'serial_con'
```

One possible solution is to check that `self.serial_con` exists before trying to set the Roomba to passive mode and close the connection in `__del__()`. Does this seem like a good solution to you? If so, I can include it in the pull request for the `SerialException` fix.

**Comment by AtsushiSakai** [comment]
Thank you for report. Could you create a PR?

**Comment by process1183** [comment]
Sure! PR #14 created.
