### ISSUE TITLE
sys.exit(1) is hard-coded in PyRoombaAdapter.__init__() and permit any retries

### ISSUE THREAD

**Issue by mrkeuz** [AtsushiSakai/PyRoombaAdapter#20]
Hi,

I found that in constructor of `PyRoombaAdapter` a `sys.exit(1)` call is hard-coded, so you cannot try to reconnect without restart python script. So if serial connect is fail you cannot as program exit with no option.

I think more flexible here is just re-raise some custom exception with human-readable message.

What you think about this?

**Comment by AtsushiSakai** [comment]
Agree. Can you create an PR?

**Comment by mrkeuz** [comment]
Yes, I'll make.
